### ISSUE TITLE
wildcard route ':id' conflicts with existing children in path

### ISSUE THREAD

**Issue by tochka** [buaazp/fasthttprouter#28]
I have the following routers, but when I run the program I see the next error
``` go
r.POST("/user/actions/search", s)
r.POST("/user/:id/collections/relations", addR)
r.DELETE("/user/:id/collections/relations", removeR)
r.GET("/user/:id", g)
r.POST("/user", a)
r.DELETE("/user/:id",d)
```

```
panic: wildcard route ':id' conflicts with existing children in path '/user/:id/collections/relations'

goroutine 1 [running]:
panic(0x29b840, 0xc420138540)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/buaazp/fasthttprouter.(*node).insertChild(0xc420012230, 0xc42004fb01, 0x31193c, 0x19, 0x311933, 0x22, 0xc4313d3410)
        /Users/user/go/src/github.com/buaazp/fasthttprouter/tree.go:237 +0xc27
github.com/buaazp/fasthttprouter.(*node).addRoute(0xc420012230, 0x311933, 0x22, 0xc4313d3410)
        /Users/user/go/src/github.com/buaazp/fasthttprouter/tree.go:193 +0x217
github.com/buaazp/fasthttprouter.(*Router).Handle(0xc4313d3320, 0x3040b0, 0x4, 0x311933, 0x22, 0xc4313d3410)
        /Users/user/go/src/github.com/buaazp/fasthttprouter/router.go:210 +0xcc
github.com/buaazp/fasthttprouter.(*Router).POST(0xc4313d3320, 0x311933, 0x22, 0xc4313d3410)
        /Users/user/go/src/github.com/buaazp/fasthttprouter/router.go:169 +0x5e
```

**Comment by buaazp** [comment]
Maybe `user_id` or `user_token` in url query string or form data is a better practice.
```
r.POST("/user/actions/search", s)
r.POST("/user/collections/relations", addR)
r.DELETE("/user/collections/relations", removeR)
r.GET("/user", g)
r.POST("/user", a)
r.DELETE("/user",d)

http "localhost:80/user/actions/search?user_id=137118"
```
