### ISSUE TITLE
GET request to POST-endpoint w/ parameters

### ISSUE THREAD

**Issue by EtienneBruines** [buaazp/fasthttprouter#29]
Maybe related to https://github.com/buaazp/fasthttprouter/issues/15, although this error is not fixed in current `master`. 

# The problem
Making a HTTP-GET request to a parameterized HTTP-POST endpoint, that does not have a defined GET endpoint. This panics (because it attempts to set the userdata / token, when no `*Context` exists (because we're still within the `allowed` method of `fasthttprouter`)). 

The URL registered would be something like `"/test/:my_parameter"`

# The log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x707672]

goroutine 22 [running]:
github.com/valyala/fasthttp.(*RequestCtx).SetUserValue(0x0, 0x81c38d, 0x5, 0x78c720, 0xc42018c100)
	/home/etiennebruines/workspaces/go/src/github.com/valyala/fasthttp/server.go:461 +0x22
github.com/buaazp/fasthttprouter.(*node).getValue(0xc42001c5f0, 0xc42018c0e1, 0xa, 0x0, 0xc42007cf30, 0x0)
	/home/etiennebruines/workspaces/go/src/github.com/buaazp/fasthttprouter/tree.go:364 +0x1ae
github.com/buaazp/fasthttprouter.(*Router).allowed(0xc4200173b0, 0xc42018c0e0, 0xb, 0xc420046bc8, 0x3, 0x0, 0xc)
	/home/etiennebruines/workspaces/go/src/github.com/buaazp/fasthttprouter/router.go:274 +0x318
github.com/buaazp/fasthttprouter.(*Router).Handler(0xc4200173b0, 0xc4200a4d80)
	/home/etiennebruines/workspaces/go/src/github.com/buaazp/fasthttprouter/router.go:354 +0x229
github.com/buaazp/fasthttprouter.(*Router).Handler-fm(0xc4200a4d80)
	/home/etiennebruines/workspaces/go/src/github.com/WebcustomsIT/shopware-bot/bot.go:42 +0x34
github.com/valyala/fasthttp.(*Server).serveConn(0xc4204be280, 0xa2a020, 0xc420118000, 0x1, 0x101)
	/home/etiennebruines/workspaces/go/src/github.com/valyala/fasthttp/server.go:1554 +0x6e4
github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0xa2a020, 0xc420118000, 0x1, 0x0)
	/home/etiennebruines/workspaces/go/src/github.com/valyala/fasthttp/server.go:1268 +0x3e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc4202ca980, 0xc42000c480)
	/home/etiennebruines/workspaces/go/src/github.com/valyala/fasthttp/workerpool.go:210 +0xd2
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc4202ca980, 0xc42000c480, 0x77a660, 0xc42000c480)
	/home/etiennebruines/workspaces/go/src/github.com/valyala/fasthttp/workerpool.go:182 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/home/etiennebruines/workspaces/go/src/github.com/valyala/fasthttp/workerpool.go:181 +0x138
exit status 2
```

# Misc
Tested on go1.7.3 and on a master-branch of Go after 1.8 release.

**Comment by buaazp** [comment]
Maybe your `fasthttprouter` is not update. The code here doesn't match with your panic log:
https://github.com/buaazp/fasthttprouter/blob/master/tree.go#L364

You need to get the latest code of `fasthttprouter` via `git pull`.

**Comment by EtienneBruines** [comment]
Apparently updating `valyala/fasthttp` isn't the same as updating `buaazp/fasthttprouter`. 

Oops, terribly sorry. Thank you for the amazing quick response, though :smile:.
